/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import apoio.Formatacao;
import apoio.TableSorter;
/*import dao.CadLocaisDAO;
import dao.CadPessoaDAO;
import dao.GrupoPessoaDAO;*/
//import entidades.CadLocais;
import entidades.Pessoa;
import entidades.Grupo_Pessoa;
import java.awt.Color;
import java.awt.TextField;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Rogério H. Klein <rhklein@universo.univates.br>
 */
public class IfrGrupo extends javax.swing.JInternalFrame {

    private static IfrGrupo tela;
    Grupo_Pessoa grupo;
    TableSorter sorter;
    
    static JInternalFrame getInstancia() {
        if (tela == null) {
            tela = new IfrGrupo();
        }
        return tela;
    }

    /**
     * Creates new form IfrGrupo
     */
    public IfrGrupo() {
        initComponents();
        grupo = new Grupo_Pessoa();
        //popula cabecalho da tabela
        ///new CadPessoaDAO().popularTabela(tblPessoasCadastro, "", 0);
        ///new CadPessoaDAO().popularTabela(tblPessoasGrupo, null, 0);
        //sorter.sorter(tblPessoasCadastro);
        //sorter.sorter(tblPessoasGrupo);
        
    }

    int idGrupo = 0;

    /*public void definirLocal(CadLocais idlocal, String local, String cidade, String endereco, String ed) {
    
    int id = idlocal.getIdLocal();
    
    CadLocais i = new CadLocaisDAO().consultarId(id);
    if (i == null) {
    JOptionPane.showMessageDialog(null, "Registro não localizado!");
    } else {
    if (ed.equals("e")) {
    grupo.setIdLocalEncontro(id);
    txfLocalEncontro.setText(local);
    txfCidadeEncontro.setText(cidade);
    txfEnderecoEncontro.setText(endereco);
    } else {
    grupo.setIdLocalDestino(id);
    txfLocalDestino.setText(local);
    txfCidadeDestino.setText(cidade);
    txfEnderecoDestino.setText(endereco);
    }
    
    }
    }*/

    /*private boolean camposObrigatorios(JTextField txfNomeGrupo, JTextField txfLocalEncontro, JTextField txfLocalDestino, JTable tblPessoasGrupo) {
    if (txfNomeGrupo.getText().equals("") || txfNomeGrupo.getText().equals(" ") || txfNomeGrupo.getText() == null) {
    JOptionPane.showMessageDialog(null, "Digite um nome para o Grupo!");
    txfNomeGrupo.setBackground(Color.yellow);
    txfNomeGrupo.requestFocus();
    return false;
    }
    if (txfLocalEncontro.getText().equals("") || txfLocalEncontro.getText().equals(" ") || txfLocalEncontro.getText() == null) {
    JOptionPane.showMessageDialog(null, "Selecione um local de Encontro!");
    txfLocalEncontro.setBackground(Color.yellow);
    txfLocalEncontro.requestFocus();
    return false;
    }
    if (txfLocalDestino.getText().equals("") || txfLocalDestino.getText().equals(" ") || txfLocalDestino.getText() == null) {
    JOptionPane.showMessageDialog(null, "Selecione um local de Destino!");
    txfLocalDestino.setBackground(Color.yellow);
    txfLocalDestino.requestFocus();
    return false;
    }
    if (tblPessoasGrupo.getRowCount() < 1) {
    JOptionPane.showMessageDialog(null, "Adicione alguma pessoa ao Grupo!");
    tblPessoasGrupo.setBackground(Color.yellow);
    tblPessoasGrupo.requestFocus();
    return false;
    }
    return true;
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPessoasCadastro = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPessoasGrupo = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txfNomeGrupo = new javax.swing.JTextField();
        txfLocalEncontro = new javax.swing.JTextField();
        txfLocalDestino = new javax.swing.JTextField();
        txfCidadeEncontro = new javax.swing.JTextField();
        txfCidadeDestino = new javax.swing.JTextField();
        txfEnderecoEncontro = new javax.swing.JTextField();
        txfEnderecoDestino = new javax.swing.JTextField();
        btnRemover = new javax.swing.JButton();
        btnLocalEncontro = new javax.swing.JButton();
        btnLocalDestino = new javax.swing.JButton();

        setTitle("Controle de Grupos");

        tblPessoasCadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPessoasCadastro);

        tblPessoasGrupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblPessoasGrupo);

        btnAdicionar.setText(">");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Selecionar Pessoa:");

        jLabel2.setText("Nome do Grupo*");

        jLabel3.setText("Pessoas do Grupo:");

        jLabel4.setText("Local Encontro");

        jLabel5.setText("Local Destino");

        jLabel6.setText("Cidade");

        jLabel7.setText("Cidade");

        jLabel8.setText("Endereço");

        jLabel9.setText("Endereço");

        txfNomeGrupo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txfNomeGrupoKeyPressed(evt);
            }
        });

        txfLocalEncontro.setEditable(false);

        txfLocalDestino.setEditable(false);

        txfCidadeEncontro.setEditable(false);

        txfCidadeDestino.setEditable(false);

        txfEnderecoEncontro.setEditable(false);

        txfEnderecoDestino.setEditable(false);

        btnRemover.setText("<");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnLocalEncontro.setText("Local");
        btnLocalEncontro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalEncontroActionPerformed(evt);
            }
        });

        btnLocalDestino.setText("Local");
        btnLocalDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalDestinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCancelar)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAdicionar)
                                    .addComponent(btnRemover))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalvar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfNomeGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txfLocalEncontro, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnLocalEncontro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txfCidadeEncontro, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txfEnderecoEncontro, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel6))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfEnderecoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfCidadeDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txfLocalDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnLocalDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfNomeGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfLocalEncontro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfLocalDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(btnLocalEncontro)
                    .addComponent(btnLocalDestino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txfCidadeEncontro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txfCidadeDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfEnderecoEncontro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfEnderecoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnAdicionar)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemover))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        tblPessoasGrupo.setBackground(null);
        TableModel model1 = tblPessoasCadastro.getModel();
        DefaultTableModel model11 = (DefaultTableModel) tblPessoasCadastro.getModel();
        int[] indexs = tblPessoasCadastro.getSelectedRows();
        int columns = tblPessoasCadastro.getColumnCount();
        Object[] row = new Object[columns];
        DefaultTableModel model2 = (DefaultTableModel) tblPessoasGrupo.getModel();

        for (int i = 0; i < indexs.length; i++) {
            for (int j = 0; j < columns; j++) {
                row[j] = model1.getValueAt(indexs[i], j);
            }
            model2.addRow(row);
            model11.removeRow(indexs[i]);
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        TableModel model1 = tblPessoasGrupo.getModel();
        DefaultTableModel model11 = (DefaultTableModel) tblPessoasGrupo.getModel();
        int[] indexs = tblPessoasGrupo.getSelectedRows();
        int columns = tblPessoasGrupo.getColumnCount();
        Object[] row = new Object[columns];
        DefaultTableModel model2 = (DefaultTableModel) tblPessoasCadastro.getModel();

        for (int i = 0; i < indexs.length; i++) {
            for (int j = 0; j < columns; j++) {
                row[j] = model1.getValueAt(indexs[i], j);
            }
            model2.addRow(row);
            model11.removeRow(indexs[i]);
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnLocalEncontroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalEncontroActionPerformed
        txfLocalEncontro.setBackground(null);
        //JdlLocal1 busca = new JdlLocal1(null, true, this, "e");
        //busca.setLocationRelativeTo(this);
        //busca.setVisible(true);
    }//GEN-LAST:event_btnLocalEncontroActionPerformed

    private void btnLocalDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalDestinoActionPerformed
        txfLocalDestino.setBackground(null);
        //JdlLocal1 busca = new JdlLocal1(null, true, this, "d");
        //busca.setLocationRelativeTo(this);
        //busca.setVisible(true);
    }//GEN-LAST:event_btnLocalDestinoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        /*if (camposObrigatorios(txfNomeGrupo, txfLocalEncontro, txfLocalDestino, tblPessoasGrupo)) {
        
        grupo.setIdGrupo(idGrupo);
        grupo.setNomeGrupo(txfNomeGrupo.getText());
        grupo.setAdmin(1);
        grupo.setStatus("A");
        
        GrupoPessoaDAO grupoDAO = new GrupoPessoaDAO();
        String retorno = grupoDAO.salvar(grupo);
        
        if (retorno == null) {
        idGrupo = grupoDAO.consultarUltimoId();
        
        CadPessoa pessoa = new CadPessoa();
        CadPessoaDAO pessoaDAO = new CadPessoaDAO();
        
        pessoa.setIdGrupo(idGrupo);
        //System.out.println("cod grupo: " + idGrupo);
        //System.out.println("cod grupo: " + pessoa.getIdGrupo());
        
        for (int i = 0; i < tblPessoasGrupo.getRowCount(); i++) {
        int codPessoa = (int) tblPessoasGrupo.getValueAt(i, 0);
        //System.out.println("Cod Pessoa: " + codPessoa);
        //System.out.println("cod grupo: " + pessoa.getIdGrupo());
        pessoa.setIdPessoa(codPessoa);
        String retorno2 = pessoaDAO.atualizarGrupo(pessoa);
        }
        
        //teste fim
        JOptionPane.showMessageDialog(null, "Registro salvo com sucesso!");
        
        // limpar campos
        txfNomeGrupo.setText("");
        txfLocalEncontro.setText("");
        txfCidadeEncontro.setText("");
        txfEnderecoEncontro.setText("");
        txfLocalDestino.setText("");
        txfCidadeDestino.setText("");
        txfEnderecoDestino.setText("");
        
        new CadPessoaDAO().popularTabela(tblPessoasCadastro, "", 0);
        new CadPessoaDAO().popularTabela(tblPessoasGrupo, null, 0);
        
        // posiciona cursor
        txfNomeGrupo.requestFocus();
        
        } else {
        JOptionPane.showMessageDialog(null, "Ops! Problemas ao salvar registro.");
        }
        
        }*/
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txfNomeGrupoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfNomeGrupoKeyPressed
        txfNomeGrupo.setBackground(null);
    }//GEN-LAST:event_txfNomeGrupoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLocalDestino;
    private javax.swing.JButton btnLocalEncontro;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPessoasCadastro;
    private javax.swing.JTable tblPessoasGrupo;
    private javax.swing.JTextField txfCidadeDestino;
    private javax.swing.JTextField txfCidadeEncontro;
    private javax.swing.JTextField txfEnderecoDestino;
    private javax.swing.JTextField txfEnderecoEncontro;
    private javax.swing.JTextField txfLocalDestino;
    private javax.swing.JTextField txfLocalEncontro;
    private javax.swing.JTextField txfNomeGrupo;
    // End of variables declaration//GEN-END:variables
}
